// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuiE1PDnZcKg33cn7oUJTBA0bIfvykuTk',
    appId: '1:596075688752:web:8e2c1c5eb542fd22880ef5',
    messagingSenderId: '596075688752',
    projectId: 'kidkash-65e33',
    authDomain: 'kidkash-65e33.firebaseapp.com',
    storageBucket: 'kidkash-65e33.firebasestorage.app',
    measurementId: 'G-50FT6TDW0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNY4qmIrJ1R-tvwKruZAkxupqJjnAUOW4',
    appId: '1:596075688752:android:b85535ca50642556880ef5',
    messagingSenderId: '596075688752',
    projectId: 'kidkash-65e33',
    storageBucket: 'kidkash-65e33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCheCnusWq9I20_H0G-co99sUn5k5fszRc',
    appId: '1:596075688752:ios:27889cbe6f21edc9880ef5',
    messagingSenderId: '596075688752',
    projectId: 'kidkash-65e33',
    storageBucket: 'kidkash-65e33.firebasestorage.app',
    iosBundleId: 'com.example.kidkash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCheCnusWq9I20_H0G-co99sUn5k5fszRc',
    appId: '1:596075688752:ios:27889cbe6f21edc9880ef5',
    messagingSenderId: '596075688752',
    projectId: 'kidkash-65e33',
    storageBucket: 'kidkash-65e33.firebasestorage.app',
    iosBundleId: 'com.example.kidkash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuiE1PDnZcKg33cn7oUJTBA0bIfvykuTk',
    appId: '1:596075688752:web:08781fbf36fa3601880ef5',
    messagingSenderId: '596075688752',
    projectId: 'kidkash-65e33',
    authDomain: 'kidkash-65e33.firebaseapp.com',
    storageBucket: 'kidkash-65e33.firebasestorage.app',
    measurementId: 'G-GCMZJS5ZNQ',
  );
}
